export * from "./AlertIcon"
export * from "./ChatIcon"
export * from "./ClipboardIcon"
export * from "./UserAddIcon"
export * from "./UsersIcon"
export * from "./UploadIcon"
export * from "./AngleArrowDownIcon"
export * from "./TimesIcon"
export * from "./CheckIcon"
export * from "./AngleArrowLeftIcon"
export * from "./CircleCheckIcon"
export * from "./CogIcon"
export * from "./ChartBarIcon"
export * from "./TemplateIcon"
export * from "./ViewGridIcon"
export * from "./ShopCartIcon"
export * from "./ErrorIcon"
export * from "./PlusCircleIcon"
export * from "./TableIcon"
export * from "./PrinterIcon"
export * from "./SwitchHorinIcon"
export * from "./UserGroupIcon"
export * from "./GlobeIcon"
export * from "./EditIcon"
export * from "./DeleteIcon"
export * from "./BanIcon"
export * from "./UserIcon"
export * from "./PlusIcon"
export * from "./ShopWhatIcon"
export * from "./ShareIcon"
export * from "./EllipsisVertIcon"
export * from "./TruckIcon"
export * from "./TwitterIcon"
export * from "./InstagramIcon"
export * from "./FacebookIcon"
export * from "./WhatsAppIcon"






